# set default task and default training config based on task
defaults:
  - task: ???
  - rl_train: ${find_rl_train_config:${task}}
  - override hydra/job_logging: disabled
  - _self_

# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''
side: 'Local'
bimanual_mode: united
dexhand: inspire
rh_base_model_checkpoint: assets/imitator_rh_inspire.pth
lh_base_model_checkpoint: assets/imitator_lh_inspire.pth

# if set to positive integer, overrides the default number of environments
num_envs: ''
rolloutStateInit: False
randomStateInit: True

rolloutLen: null
rolloutBegin: null

learning_rate: 5e-4
actionsMovingAverage: 1.0

usePIDControl: False

dataIndices: [7]

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: 9999999999999  # train forever
early_stop_epochs: 9999999999999

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# save rollouts config, used for distillation
save_rollouts: False
save_successful_rollouts_only: True
num_rollouts_to_save: 20000
num_rollouts_to_run: 9999999999999
min_episode_length: 20
# used to set checkpoint path
checkpoint: ''
from_ckpt_epoch: false
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: ${rl_train.params.config.name}
wandb_entity: null  # set to your wandb entity if using wandb
wandb_project: null  # set to your wandb project if using wandb
wandb_tags: []
wandb_logcode_dir: '' 

capture_video: False
n_parallel_recorders: 8
n_successful_videos_to_record: 50
display: False
headless: True

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .
